[project]
name = "nupgis"
version = "0.1.2"
description = "A Python library for GIS using numpy only."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
]

[dependency-groups]
dev = [
    "coverage>=7.8.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
]
docs = [
    "furo>=2024.8.6",
    "sphinx>=8.2.3",
]
formatting = [
    "pre-commit>=4.2.0",
]


[tool.ruff]
exclude = [".venv"]
line-length = 120
target-version = "py311"


[tool.bandit.assert_used]
skips = ['*_test.py', '*/test_*.py']
